// Command registry-doc rewrites the catalogue table in README.md from the
// recipes themselves, so the list a reader sees is the list block will
// install.
//
//	registry-doc            # rewrite the table between the markers in README.md
//	registry-doc -check     # fail if the committed table is not what the recipes say
//
// The website renders its catalogue straight from registry/*.toml at build
// time and needs nothing from here; this exists because a README is read on
// GitHub, where no template runs.
//
// The recipe struct below is deliberately a small, separate view of the file
// format: this tool needs five fields, and registry-lint — which needs every
// field, and carries a lint method per field — stays the one definition of
// what a valid recipe is.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
)

// Markers delimit the generated block. Everything between them is replaced;
// everything outside is written by hand and never touched.
const (
	beginMarker = "<!-- BEGIN CATALOG (generated by \"make doc\"; edit the recipes, not this table) -->"
	endMarker   = "<!-- END CATALOG -->"
	readmePerm  = 0o600
)

type recipe struct {
	Name        string   `toml:"name"`
	Ecosystems  []string `toml:"ecosystems"`
	Description string   `toml:"description"`
	Source      struct {
		Repo string   `toml:"repo"`
		Bin  []string `toml:"bin"`
	} `toml:"source"`
}

func main() {
	dir := flag.String("dir", "registry", "directory holding the recipes")
	readme := flag.String("readme", "README.md", "file whose catalogue block is rewritten")
	check := flag.Bool("check", false, "compare instead of writing, and exit 1 on a difference")
	flag.Parse()

	if err := run(*dir, *readme, *check); err != nil {
		fmt.Fprintf(os.Stderr, "registry-doc: %v\n", err)
		os.Exit(1)
	}
}

func run(dir, readme string, check bool) error {
	recipes, err := load(dir)
	if err != nil {
		return err
	}
	current, err := os.ReadFile(filepath.Clean(readme))
	if err != nil {
		return err
	}
	want, err := replace(string(current), table(recipes))
	if err != nil {
		return err
	}
	if check {
		if string(current) != want {
			return fmt.Errorf("%s is stale; run \"make doc\"", readme)
		}
		return nil
	}
	return os.WriteFile(filepath.Clean(readme), []byte(want), readmePerm)
}

// load reads every recipe in dir, sorted by tool name.
func load(dir string) ([]recipe, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var out []recipe
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".toml") {
			continue
		}
		data, err := os.ReadFile(filepath.Clean(filepath.Join(dir, e.Name())))
		if err != nil {
			return nil, err
		}
		var r recipe
		if _, err := toml.Decode(string(data), &r); err != nil {
			return nil, fmt.Errorf("%s: %w", e.Name(), err)
		}
		if r.Name == "" {
			return nil, fmt.Errorf("%s: recipe has no name", e.Name())
		}
		out = append(out, r)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}

// table renders the catalogue: a count, then one row per blockchain system
// naming its tools and the commands they provide.
func table(recipes []recipe) string {
	byEcosystem := map[string][]recipe{}
	for _, r := range recipes {
		for _, e := range r.Ecosystems {
			byEcosystem[e] = append(byEcosystem[e], r)
		}
	}
	ecosystems := make([]string, 0, len(byEcosystem))
	for e := range byEcosystem {
		ecosystems = append(ecosystems, e)
	}
	sort.Strings(ecosystems)

	var b strings.Builder
	fmt.Fprintf(&b, "%d tools across %d blockchain systems, enough that a project's toolchain —\nnode, compiler, test runner, relayer — can be pinned without reaching for\nanything else.\n\n", len(recipes), len(ecosystems))
	b.WriteString("| Ecosystem | Tools |\n| --- | --- |\n")
	for _, e := range ecosystems {
		names := make([]string, 0, len(byEcosystem[e]))
		for _, r := range byEcosystem[e] {
			names = append(names, "`"+r.Name+"`")
		}
		fmt.Fprintf(&b, "| %s | %s |\n", e, strings.Join(names, ", "))
	}
	b.WriteString("\nThe commands each of them puts on your PATH are in the\n[catalog](https://nao1215.github.io/block-registry/#catalog), rendered from\nthese same files.\n")
	return b.String()
}

// replace swaps the text between the markers, leaving the markers in place.
func replace(doc, generated string) (string, error) {
	begin := strings.Index(doc, beginMarker)
	end := strings.Index(doc, endMarker)
	if begin < 0 || end < 0 || end < begin {
		return "", fmt.Errorf("the catalogue markers are missing or out of order; expected %s ... %s", beginMarker, endMarker)
	}
	var b bytes.Buffer
	b.WriteString(doc[:begin+len(beginMarker)])
	b.WriteString("\n\n")
	b.WriteString(generated)
	b.WriteString("\n")
	b.WriteString(doc[end:])
	return b.String(), nil
}
